In [1]:
import numpy as np

arr_x = np.zeros(shape=(4,1))
arr_y = np.zeros(shape=(4,1))

arr_x[2] = 1
arr_y[0] = arr_y[2] = 1

print("X: ")
print(arr_x)
print("Y: ")
print(arr_y)

X: 
[[0.]
 [0.]
 [1.]
 [0.]]
Y: 
[[1.]
 [0.]
 [1.]
 [0.]]


In [2]:
arr_z = np.matmul(arr_x, arr_y.T)
print("Z: ")
print(arr_z)

Z: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]]


In [3]:
arr = np.tile(A=arr_x,reps=4)
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

In [4]:
arr_ones = np.ones(shape=(4,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
exp_matrix = np.multiply(arr_x, arr_z)

print("Matrix: ")
print(exp_matrix)

Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]]


In [6]:
# arr_values = np.arange(start=0.0, stop=1.0, step=4, dtype=np.float64)
arr_values = np.random.rand(4,4,)

arr_values

array([[0.05361928, 0.67111678, 0.41048301, 0.78362076],
       [0.87145146, 0.7182351 , 0.05861774, 0.04906116],
       [0.16814996, 0.43951401, 0.4234614 , 0.17388352],
       [0.77687704, 0.23848178, 0.86779562, 0.78540239]])

In [7]:
masked_array = exp_matrix * arr_values
masked_array

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.16814996, 0.        , 0.4234614 , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [8]:
# logical_arr = arr_ones == 1.0
logical_arr = exp_matrix == 1.0
logical_arr

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False,  True, False],
       [False, False, False, False]])

In [9]:
arr_logical_or = np.logical_xor(exp_matrix == 1.0, arr_ones == 1.0)
arr_logical_or

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True, False,  True],
       [ True,  True,  True,  True]])

In [10]:
arr_test_value = 1 * arr_logical_or

arr_test_value

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 1, 0, 1],
       [1, 1, 1, 1]])

In [11]:
import numpy as np
values_len = 4

arr_test_value = arr_values * np.mean(arr_values) * (np.sqrt(2) ** (1/(np.std(arr_values)+1)))
print(arr_values)
print("\n")
print(arr_test_value)
        

[[0.05361928 0.67111678 0.41048301 0.78362076]
 [0.87145146 0.7182351  0.05861774 0.04906116]
 [0.16814996 0.43951401 0.4234614  0.17388352]
 [0.77687704 0.23848178 0.86779562 0.78540239]]


[[0.03274563 0.4098553  0.25068459 0.47856219]
 [0.53220096 0.43863075 0.03579823 0.02996196]
 [0.10269025 0.268414   0.25861057 0.10619178]
 [0.47444376 0.14564234 0.52996831 0.47965024]]


In [12]:
arr_test_value = arr_test_value * np.mean(arr_test_value) * (np.sqrt(2) ** (1/(np.std(arr_test_value)+1)))
print(arr_test_value)

[[0.01254077 0.15696446 0.09600601 0.18327751]
 [0.20381983 0.16798475 0.01370984 0.01147469]
 [0.03932783 0.10279594 0.09904147 0.04066883]
 [0.18170025 0.05577742 0.20296479 0.18369421]]


In [16]:
arr_scores = np.random.rand(4,4)
print(arr_scores)
print("\n")
print(np.mean(arr_scores, axis=0))
print(np.mean(arr_scores, axis=1))

[[0.52655574 0.13731766 0.57792377 0.68741294]
 [0.36046028 0.51930091 0.01376963 0.6579754 ]
 [0.44779589 0.05453266 0.16907439 0.22703477]
 [0.67426679 0.33011248 0.36075912 0.2758628 ]]


[0.50226967 0.26031593 0.28038173 0.46207148]
[0.48230253 0.38787656 0.22460943 0.4102503 ]


In [26]:
# arr_scores[:,0]
arr_neg_scores = -arr_scores

arr_neg_scores = np.fabs(arr_neg_scores)
arr_neg_scores


array([[0.52655574, 0.13731766, 0.57792377, 0.68741294],
       [0.36046028, 0.51930091, 0.01376963, 0.6579754 ],
       [0.44779589, 0.05453266, 0.16907439, 0.22703477],
       [0.67426679, 0.33011248, 0.36075912, 0.2758628 ]])